### ISSUE TITLE
String aSurfaceFiltersString;

### ISSUE THREAD

**Issue by tischi** [BIOP/EasyXT-FIJI#15]
@NicoKiaru 
Do you know what values one can put there?
`String aSurfaceFiltersString;`
Specifically, we would like to exclude surfaces touching the image border.

**Comment by NicoKiaru** [comment]
Hi @tischi, 

So we try to stick completely to the Imaris API variable name. If you have Imaris installed on your computer, you can check the header of this class: 

https://github.com/BIOP/EasyXT-FIJI/blob/d49aee5873397a11b3c9a06221741c59a882c4f0/src/main/java/ch/epfl/biop/imaris/SurfacesDetector.java#L51-L52

You have links towards the Imaris API and hopefully what you can enter will be explained.

**Comment by NicoKiaru** [comment]
> Specifically, we would like to exclude surfaces touching the image border.

Can't you do this in FIJI ?

**Comment by tischi** [comment]
> Can't you do this in FIJI ?

Probably yes, I could loop through the Surface objects....
But maybe easier to do it in Imaris? I will have a look at the API!

**Comment by tischi** [comment]
I figured it out, I think. 

In the Creation Parameters
```
[Algorithm]
  Enable Region Of Interest = false
  Enable Region Growing = false
  Enable Tracking = false
  Enable Classify = false
  Enable Shortest Distance = true
[Source Channel]
  Source Channel Index = 3
  Enable Smooth = true
  Surface Grain Size = 0.130 µm
  Enable Eliminate Background = false
  Diameter Of Largest Sphere = 0.488 µm
[Threshold]
  Enable Automatic Threshold = true
  Manual Threshold Value = 9.65796
  Active Threshold = true
  Enable Automatic Threshold B = true
  Manual Threshold Value B = 45.6801
  Active Threshold B = false
[Filter Surfaces]
  "Number of Voxels Img=1" above 10  <= This one!
```
One can probably just copy and paste the last entry.

**Comment by tischi** [comment]
For excluding objects touching the image border:
```
"Distance to Image Border XYZ Img=1" above 0.001 um
```

**Comment by tischi** [comment]
Not sure what the `Img=1` means, but ok...

**Comment by romainGuiet** [comment]
>Not sure what the Img=1 means, but ok...
Actually I think it's not necessary to make the filter work

**Comment by lacan** [comment]
This is linked to the Imaris spagetti from the latest versions. 
Because now you could add multiple datasets in a single IMS to register them (Like EM plus fluorescence). So that option (which for some weird reason is one-based) selects the image upon which the filter should be applied (different images will have different bounds, so that makes sense).
