### ISSUE TITLE
Add Child to Scene Index

### ISSUE THREAD

**Issue by tischi** [BIOP/EasyXT-FIJI#16]
@lacan 
What is the meaning of the index `i`?
`EasyXT.getImaris().GetSurpassScene().AddChild(nuclei,i);`

**Comment by romainGuiet** [comment]
>What is the meaning of the index i?

from ".../Bitplane/Imaris%20x64%209.5.1/html/xtinterface/structImaris_1_1IDataContainer.html"
The index defines the position (counting starts at 0, while -1 appends it as the last child).
