### ISSUE TITLE
Surfaces.getLabelsImage() is no longer a label because of ImageConverter

### ISSUE THREAD

**Issue by romainGuiet** [BIOP/EasyXT-FIJI#31]
In the obtained imp pixels are only 0/255 instead of labels value

https://github.com/BIOP/EasyXT-FIJI/blob/94246c3843bdc71a15c2d8b7141777c0591695e5/src/main/java/ch/epfl/biop/imaris/EasyXT.java#L1408

**Comment by lacan** [comment]
Commit 347c1171c215b2425d2933d22cd4fc90d2a4e2cd should fix this. Let me know and I will add it to the update site

**Comment by romainGuiet** [comment]
it does !
