### ISSUE TITLE
Issue with 2D images from Imaris

### ISSUE THREAD

**Issue by lguerard** [BIOP/EasyXT-FIJI#39]
Hi guys,

When trying to use EasyXT on a 2D image with surfaces, the following line gave an issue as it complained that HyperStack need to have stacks (makes sense in a way).

https://github.com/BIOP/EasyXT-FIJI/blob/0612b87147b606d8349559fe9deb6bb76cc96442/src/main/java/ch/epfl/biop/imaris/EasyXT.java#L993

I tried changing it to 

```java
if (nz != 1 && nt != 1)
    imp = HyperStackConverter.toHyperStack(imp, nc, nz, nt);
```

but the Fiji plugin returns a completely black picture. 

Would have an idea on how to fix this ?

Thanks !

**Comment by NicoKiaru** [comment]
I think we did not put any demos with 2D images, so I'm not really surprised that it does not work.

Would you be able to provide a small minimally self-contained failing example as a script ? (maybe with blobs ? is it possible?)

**Comment by romainGuiet** [comment]
just try this , and it's working : 
```
import ij.*;
import ch.epfl.biop.imaris.EasyXT

IJ.run("Close All", "");

try2D = false
ImagePlus imp = new ImagePlus()

if (try2D){
	imp = IJ.openImage("http://imagej.nih.gov/ij/images/blobs.gif");
	IJ.run(imp, "Invert LUT", "");
}else{
	imp = IJ.openImage("http://imagej.nih.gov/ij/images/Spindly-GFP.zip");
}

dataset = EasyXT.Dataset.create(imp)
EasyXT.Dataset.setCurrent(dataset)
```

**Comment by romainGuiet** [comment]
and with a surface it works too : 
```
import ij.*;
import ch.epfl.biop.imaris.EasyXT

IJ.run("Close All", "");

try2D = false
ImagePlus imp = new ImagePlus()

if (try2D){
	imp = IJ.openImage("http://imagej.nih.gov/ij/images/blobs.gif");
	IJ.run(imp, "Invert LUT", "");
}else{
	imp = IJ.openImage("http://imagej.nih.gov/ij/images/Spindly-GFP.zip");
}


dataset = EasyXT.Dataset.create(imp)
EasyXT.Dataset.setCurrent(dataset)


surf = EasyXT.Surfaces.create(0)
        .setSmoothingWidth(1)
		.enableAutomaticLowerThreshold() // default behavior
		//.setLowerThreshold(80) // possible to change value to a defined one
        .setSurfaceFilter('"Volume" above 1.0 um^3')
        .setName("Nuclei")
        .build()
        .detect()
        
EasyXT.Scene.addItem(surf)
```

**Comment by NicoKiaru** [comment]
Thanks Romain ! So please @lguerard let us know if you have a script which fails.

Also, which version of the plugin do you have ? (it should be EasyXT-0.2.13). And which version of Imaris do you use ?

**Comment by lguerard** [comment]
Thanks both ! :) 

I'm not fully familiar with EasyXT but I guess that here @romainGuiet you're going from Fiji to Imaris. My issues were with going from Imaris to Fiji.

To describe the steps I did and got errors : 
* Go to Imaris (9.8)
* Open a 2D image there OR
    * Open any of the default image
    * Crop 3D to keep only 1Z
* Make a surface on that image
* Then in Fiji, using latest version of the plugin, go to EasyXT > Surface > Get Surface and it returns a black image

 Let me know if it's unclear, I'd be happy to have a (even 5min) meeting with you to look into it :)

Thanks again !

**Comment by romainGuiet** [comment]
Hi @lguerard 

> I'm not fully familiar with EasyXT 

No one really is 😁 

This code replicate your issue "Stack required" with a 2D image

```
import ij.*;
import ch.epfl.biop.imaris.EasyXT
import Imaris.*

EasyXT.Scene.reset()
IJ.run("Close All", "");

try2D = 1
ImagePlus imp = new ImagePlus()

if (try2D){
	imp = IJ.openImage("http://imagej.nih.gov/ij/images/blobs.gif");
	IJ.run(imp, "Invert LUT", "");
}else{
	imp = IJ.openImage("http://imagej.nih.gov/ij/images/Spindly-GFP.zip");
}

// load an image in Imaris, 2D or 3D depending of try2D  true or flase
dataset = EasyXT.Dataset.create(imp)
EasyXT.Dataset.setCurrent(dataset)

// Here EasyXT makes Imaris create/detect a Surfaces object : "surf"
surf = EasyXT.Surfaces.create(0)
        .setSmoothingWidth(1)
		.enableAutomaticLowerThreshold() // default behavior
		//.setLowerThreshold(80) // possible to change value to a defined one
        .setSurfaceFilter('"Volume" above 1.0 um^3')
        .setName("Nuclei")
        .build()
        .detect()

// we now add "surf" to the scene 
EasyXT.Scene.addItem(surf)

// Here we can retrieve
getSurf = EasyXT.Scene.findSurfaces("Nuclei")

// Here we produce an error : "Stack required" if the image is 2D
//mask_imp = EasyXT.Surfaces.getMaskImage( surf  )
mask_imp = EasyXT.Surfaces.getMaskImage( getSurf  ) 
mask_imp.show()
```

**Comment by lguerard** [comment]
Hi @romainGuiet,

Thanks for looking into it and managing to reproduce the error ! 

Is there anything I can try and do to help in finding out a solution ? :)

**Comment by NicoKiaru** [comment]
@lguerard it should work now. The fix has been pushed to the update site

**Comment by lguerard** [comment]
It is indeed not failing anymore but the image is completely black somehow. I tried both through the Fiji GUI or via @romainGuiet's script. Is it working for you ?
